exec_module: 'run_all_checks_from_files'

bilara_root_path: "./bilara-data/root/"
# Allows us to include more than just the Pali in the root tests
bilara_root_langs: ['pli/ms/', 'lzh/']
bilara_html_path: "./bilara-data/html"
bilara_comment_path: "./bilara-data/comment"
bilara_variant_path: "./bilara-data/variant"
bilara_translation_path: "./bilara-data/translation"
reference_root_path: "./bilara-data/reference/pli/ms"

# Not used in GitHub Action
ms_yuttadhammo_path: "./sc-renumber-segments/data/ms_yuttadhammo"
pali_concordance_filepath: "./sc-renumber-segments/data/all_pali_concordance.json"
pali_canon_path: "~/ms_palicanon"

exclude_dirs: ['name', 'xplayground', 'vri', 'site', 'blurb']
exclude_filepath: './false_positives.yaml'

# Path where check_migration script result will be saved.
# It should point to the migration_differences folder in the Bilara-data project.
migration_differences_path: "./bilara-data/migration_differences"


debug_dir: "."
# Log level: [0, 50]. 10-debug, 20-info, 30-warning, 40-error, 50-critical
log_level: 40
